// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node_conn.proto

package com.grpcLEDservice.grpc;

public final class NodeConn {
  private NodeConn() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
