// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node_conn.proto

package com.grpcLEDservice.grpc;

public interface TextMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TextMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
