# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coreBoardCommuService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import domain_pb2 as domain__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63oreBoardCommuService.proto\x1a\x0c\x64omain.proto2\x81\x02\n\x15\x43oreBoardCommuService\x12\x37\n\x0fstartSimulacion\x12\x13.SimulacionBoardReq\x1a\r.MensajeReply\"\x00\x12\x34\n\x13getSimulacionActual\x12\t.EmptyReq\x1a\x10.SimulacionReply\"\x00\x12;\n\x13getLecturasSensores\x12\t.EmptyReq\x1a\x15.LecturaSensoresReply\"\x00\x30\x01\x12<\n\x14sendMensajeEncendido\x12\x0f.SaludoBoardReq\x1a\x11.SaludoBoardReply\"\x00\x42\x1e\n\x1c\x63l.ucn.fondef.sata.mini.grpcb\x06proto3')



_COREBOARDCOMMUSERVICE = DESCRIPTOR.services_by_name['CoreBoardCommuService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034cl.ucn.fondef.sata.mini.grpc'
  _COREBOARDCOMMUSERVICE._serialized_start=46
  _COREBOARDCOMMUSERVICE._serialized_end=303
# @@protoc_insertion_point(module_scope)
